# Generated by Django 4.0.1 on 2022-02-09 22:30

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, db_index=True, editable=False, help_text='Publication UUID', max_length=22, primary_key=True, serialize=False, unique=True)),
                ('project_name', models.TextField(max_length=200)),
                ('project_url', models.TextField(default='#', max_length=400)),
            ],
            options={
                'verbose_name': 'comren_project',
                'verbose_name_plural': 'comren_projects',
                'db_table': 'comren_projects',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, db_index=True, editable=False, help_text='Publication UUID', max_length=22, unique=True)),
                ('publication_short', models.CharField(max_length=100, unique=True)),
                ('publication', models.TextField(max_length=300)),
                ('publication_link', models.TextField(default='#', max_length=300)),
            ],
            options={
                'verbose_name': 'publication_short',
                'verbose_name_plural': 'publication_shorts',
                'db_table': 'comren_publications',
            },
        ),
    ]
