# Generated by Django 4.0.1 on 2022-01-17 00:30

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, db_index=True, editable=False, help_text='Publication UUID', max_length=22, unique=True)),
                ('publication_short', models.CharField(max_length=50, unique=True)),
                ('publication', models.TextField(max_length=250)),
            ],
            options={
                'verbose_name': 'comren_publications',
                'verbose_name_plural': 'comren_publications',
                'db_table': 'comren_publications',
            },
        ),
    ]
