# Generated by Django 4.0.1 on 2022-01-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post_n_Publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'publication_short', 'verbose_name_plural': 'publication_short'},
        ),
    ]
