# Generated by Django 4.0.1 on 2022-01-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post_n_Publication', '0002_alter_publication_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_short',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
