# Generated by Django 4.0.1 on 2022-01-17 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post_n_Publication', '0003_alter_publication_publication_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'publication_short'},
        ),
    ]
