# Generated by Django 4.0.1 on 2022-01-17 15:35

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Post_n_Publication', '0004_alter_publication_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, db_index=True, editable=False, help_text='Publication UUID', max_length=22, unique=True)),
                ('project_name', models.TextField(max_length=200)),
                ('project_url', models.TextField(max_length=400)),
            ],
        ),
    ]
