# Generated by Django 4.0.1 on 2022-01-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post_n_Publication', '0005_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'comren_project', 'verbose_name_plural': 'comren_projects'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'publication_short', 'verbose_name_plural': 'publication_shorts'},
        ),
        migrations.AlterModelTable(
            name='project',
            table='comren_projects',
        ),
    ]
